### ISSUE TITLE
I try the script and i receive this error

### ISSUE THREAD

**Issue by casperverse** [kasimbana/amazono#1]
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3700
    at Server.setupListenHandle [as _listen2] (net.js:1330:14)
    at listenInCluster (net.js:1378:12)
    at Server.listen (net.js:1466:7)
    at Function.listen (/amazono-master/server/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/amazono-master/server/server.js:27:5)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1357:8)
    at process._tickCallback (internal/process/next_tick.js:174:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by chanjungkim** [comment]
Have you solved this issue??
